name: Deploy VitePress site to Gitee Pages

on:
  # 在推送到 main 分支时运行
  push:
    branches: [main]
  # 允许从 Actions 页面手动触发工作流
  workflow_dispatch:

jobs:
  # 构建工作
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      
      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 18
      
      - name: Setup pnpm
        uses: pnpm/action-setup@v2
        with:
          version: 8
          run_install: false
      
      - name: Get pnpm store directory
        shell: bash
        run: |
          echo "STORE_PATH=$(pnpm store path --silent)" >> $GITHUB_ENV
      
      - name: Setup pnpm cache
        uses: actions/cache@v3
        with:
          path: ${{ env.STORE_PATH }}
          key: ${{ runner.os }}-pnpm-store-${{ hashFiles('**/pnpm-lock.yaml') }}
          restore-keys: |
            ${{ runner.os }}-pnpm-store-
      
      - name: Install dependencies
        run: pnpm install
      
      - name: Build with VitePress
        run: pnpm docs:build
      
      - name: Deploy to Gitee Pages
        uses: yanglbme/gitee-pages-action@main
        with:
          # Gitee 用户名
          gitee-username: ykxstore
          # Gitee 仓库名
          gitee-repo: speed-components-ui
          # Gitee 仓库分支
          branch: gh-pages
          # 部署目录
          directory: docs/.vitepress/dist
          # Gitee 私人令牌
          gitee-password: ${{ secrets.GITEE_TOKEN }} 